[env]
# in rare cases, docker hub can timeout, and we want our CI runs to be as resilient as possible
DOCKER_CLIENT_TIMEOUT = 300

PRODUCTION_CONTAINER_REGISTRY = "ghcr.io"
PRODUCTION_GITHUB_REPOSITORY = "railwayapp/railpack"
PRODUCTION_MISE_TAG = "mise-${RAILPACK_MISE_VERSION}"

PRODUCTION_BUILDER_IMAGE_NAME = "${PRODUCTION_CONTAINER_REGISTRY}/${PRODUCTION_GITHUB_REPOSITORY}-builder"
PRODUCTION_BUILDER_IMAGE_REF = "${PRODUCTION_BUILDER_IMAGE_NAME}:${PRODUCTION_MISE_TAG}"

PRODUCTION_RUNTIME_IMAGE_NAME = "${PRODUCTION_CONTAINER_REGISTRY}/${PRODUCTION_GITHUB_REPOSITORY}-runtime"
PRODUCTION_RUNTIME_IMAGE_REF = "${PRODUCTION_RUNTIME_IMAGE_NAME}:${PRODUCTION_MISE_TAG}"

