[package]
name = "rust-open-ssl"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl = "0.10.73"
openssl-sys = "0.9.109"
ring = "0.17.14"
