name: Build Documentation

on:
  push:
    branches: [main]
    paths:
      - "docs/**"
  pull_request:
    branches: [main]
    paths:
      - "docs/**"

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: docs

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - uses: jdx/mise-action@5ac50f778e26fac95da98d50503682459e86d566

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build documentation site
        run: bun run build
